PORT 7057 add aws exporter to the terraform module
port-labs/terraform-ocean-integration-factory pull request #7
Opened 2024-05-21 21:00 UTC by shalev007

- **feat: initial aws ecs app**
- **refactor: ignore temp files**
- **feat: add template ecs app**
- **feat: add role permissions**
- **fix: wrong security group error**
- **feat: add a certificate arn**
- **feat: add events**
- **fix: missing correct endpoint**
- **feat: remove certificate arn**
- **feat: remove almost all TODOs**
- **feat: add description to output**

2024-05-26 14:15 UTC, erikzaadi reviewed
`terraform fmt` is a friend

2024-05-26 14:15 UTC, erikzaadi commented on examples/aws_container_app/variables.tf
> +  }
add `validation` to make sure it's either KAFKA or POLLING

2024-05-26 14:15 UTC, erikzaadi commented on modules/aws_helpers/ecs_service/main.tf
> +      name  = upper("OCEAN__INITIALIZE_PORT_RESOURCES"),
UPPERANTLY, the upper here is not needed

2024-05-26 14:15 UTC, erikzaadi commented on modules/aws_helpers/ecs_service/main.tf
> +      name = upper("OCEAN__EVENT_LISTENER")
UPPAPER

2024-05-26 16:01 UTC, Tankilevitch requested changes

2024-05-26 16:01 UTC, Tankilevitch commented
Add readme

2024-05-26 16:02 UTC, Tankilevitch commented on examples/aws_container_app/main.tf
> +  count = var.allow_incoming_requests ? 1 : 0
❤️

2024-05-27 11:37 UTC, shalev007 commented on modules/aws_helpers/events/main.tf
can be done but since almost every event rule has different values each custom module will have almost the same amount of properties as native modules, in my opinion it's just duplicated code at this stage, WDYT?
![image](https://github.com/port-labs/terraform-ocean-integration-factory/assets/51760613/576bd507-d489-43de-8068-dc1001b6cd05)

2024-05-28 15:14 UTC, Tankilevitch requested changes

2024-05-28 15:14 UTC, Tankilevitch commented on examples/aws_container_app/README.MD
> +  allow_incoming_requests   = true
lets organize it in order of sections, port stuff first, real time events, then cloud configuration

2024-05-28 15:14 UTC, Tankilevitch commented on examples/aws_container_app/README.MD
> +
no need to clone the repository see other examples of installations, you can import examples as well

2024-05-28 15:14 UTC, Tankilevitch commented on examples/aws_container_app/main.tf
> +# }
remove?

2024-05-28 15:14 UTC, Tankilevitch commented on examples/aws_container_app/main.tf
> +#   target_arn    = var.allow_incoming_requests ? module.api_gateway[0].integration_webhook_api_arn : ""
remove

2024-05-28 15:14 UTC, Tankilevitch commented on examples/aws_container_app/README.MD
> +### Steps to Deploy
where is the example on how user uses your new `event` module?

2024-05-28 16:03 UTC, shalev007 commented on modules/aws_helpers/ecs_service/main.tf
> +  deployment_maximum_percent         = "200"
This is not for multiple containers running in the same time, `deployment_maximum_percent` cannot be the same as `deployment_minimum_healthy_percent`
https://stackoverflow.com/questions/40731143/what-is-the-minimum-healthy-percent-and-maximum-percent-in-amazon-ecs

2024-05-28 16:05 UTC, shalev007 commented on examples/aws_container_app/README.MD
> +- `vpc_id` (optional): VPC ID where the cluster will be created.
you don't have to use an existing one, the terraform will create a cluster for you
WIP: check out if I can utilize a "get or create" mode

2024-05-28 19:46 UTC, shalev007 commented on examples/aws_container_app/README.MD
> +- `allow_incoming_requests`: Boolean to allow incoming requests to the ECS tasks.
No, I just used the variables that are essential for a working installation, we could use all of the variables

2024-05-29 12:17 UTC, Tankilevitch approved these changes
well done 🚀

2024-05-29 12:17 UTC, Tankilevitch commented on examples/aws_container_app/README.MD
> +  source = "./path-to-your-module"
change to use the example path

2024-05-29 12:17 UTC, Tankilevitch commented on examples/aws_container_app/README.MD
> +  source = "./path-to-your-module"
in both docs references

2024-05-29 16:17 UTC, shalev007 commented on examples/aws_container_app/README.MD
> +  source = "./path-to-your-module"
WDYM both?

2024-05-29 16:17 UTC, merged